name: Check and create subdomains
on:
  push:
    branches:
      - main
       
jobs:
  Check_route53_entry:
    name: username and password check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set variables
      run: |
        HZ=$(cat HZONE)
        echo "HZONE=$HZ" >> $GITHUB_ENV
        R=$(cat RRS)
        echo "RRS=$R" >> $GITHUB_ENV
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
        aws-region: us-east-1
    - name: Check route53 enteries
      run: | 
        echo ${{ env.HZONE }}
        echo ${{ env.RRS }}
        aws route53 list-hosted-zones
        aws route53 list-resource-record-sets  --hosted-zone-id $HZONE  --query "ResourceRecordSets[?Name == '$RRS']"
  
